apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.10.2
        imagePullPolicy: IfNotPresent
        
        env:
        
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "false"
        
        - name: AIRFLOW__CORE__EXECUTOR
          value: "SequentialExecutor"
        
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "sqlite:////opt/airflow/airflow.db"
        
        - name: _AIRFLOW_DB_UPGRADE
          value: "true"
        
        - name: _AIRFLOW_WWW_USER_CREATE
          value: "true"
        
        - name: _AIRFLOW_WWW_USER_USERNAME
          value: "admin"
        
        - name: _AIRFLOW_WWW_USER_PASSWORD
          value: "admin"
        
        - name: DESTINATION__CREDENTIALS
          value: "postgres://postgres:QJ9dPbEPh6ojikGMX8kDbA@postgres:5432/warehouse"
        
        - name: DATA_DB_HOST
          value: "postgres"
        
        - name: DATA_DB_PORT
          value: "5432"
        
        - name: DATA_DB_USER
          value: "postgres"
        
        - name: DATA_DB_PASSWORD
          value: "QJ9dPbEPh6ojikGMX8kDbA"
        
        - name: DATA_DB_NAME
          value: "warehouse"
        
        
        
        ports:
        
        - containerPort: 8080
        
        