apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        imagePullPolicy: IfNotPresent
        
        env:
        
        - name: MB_DB_TYPE
          value: "postgres"
        
        - name: MB_DB_DBNAME
          value: "metabase"
        
        - name: MB_DB_PORT
          value: "5432"
        
        - name: MB_DB_USER
          value: "metabase"
        
        - name: MB_DB_PASS
          value: "metabase"
        
        - name: MB_DB_HOST
          value: "metabase-db"
        
        - name: DATA_WAREHOUSE_TYPE
          value: "postgres"
        
        - name: DATA_WAREHOUSE_HOST
          value: "postgres"
        
        - name: DATA_WAREHOUSE_PORT
          value: "5432"
        
        
        
        ports:
        
        - containerPort: 3000
        
        