apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-db
  labels:
    app: metabase-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase-db
  template:
    metadata:
      labels:
        app: metabase-db
    spec:
      containers:
      - name: metabase-db
        image: postgres:15
        imagePullPolicy: IfNotPresent
        
        env:
        
        - name: POSTGRES_DB
          value: "metabase"
        
        - name: POSTGRES_USER
          value: "metabase"
        
        - name: POSTGRES_PASSWORD
          value: "metabase"
        
        
        